import { ClassTile } from '@/app/page';

export const classes: ClassTile[] = [
    {
        courseCode: 'MS-110L',
        creditHours: 1,
        courseName: 'Applied Physics Lab',
        startTime: 510,
        duration: 180,
        place: 'GT-7',
        logoName: 'SA',
        teacherName: 'Sir Shoaib Ahmed',
        teacherStatus: 'Lecturer',
        day: 'mon',
        classLink: '',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'MS-103',
        creditHours: 3,
        courseName: 'Calculus & Analytical Geometry',
        startTime: 690,
        duration: 60,
        place: 'CG-6',
        logoName: 'MS',
        teacherName: 'Miss Sana Moiz',
        teacherStatus: 'Lecturer',
        day: 'mon',
        classLink: 'https://teams.microsoft.com/meet/43300871594182?p=G4JveNi3szPn7Mzwqs',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'SE-103L',
        creditHours: 1,
        courseName: 'Object Oriented Programming Lab',
        startTime: 690,
        duration: 180,
        place: 'CG-5',
        logoName: 'MS',
        teacherName: 'Miss Sana Waseem',
        teacherStatus: 'Lecturer',
        day: 'wed',
        classLink: 'https://teams.microsoft.com/meet/4456373825150?p=CILbyaOBsINfsvHGdH',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'SE-106T',
        creditHours: 2,
        courseName: 'Introduction To Software Engineering Theory',
        startTime: 870,
        duration: 120,
        place: 'CG-2',
        logoName: 'MS',
        teacherName: 'Miss Sarwat Fawwad',
        teacherStatus: 'Lecturer',
        day: 'wed',
        classLink: 'https://teams.microsoft.com/meet/49970201252186?p=7lUPHOBiAYoUFjJvik',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'MS-110T',
        creditHours: 3,
        courseName: 'Applied Physics Theory',
        startTime: 990,
        duration: 60,
        place: 'CG-2',
        logoName: 'MS',
        teacherName: 'Miss Sabeen Akhtar',
        teacherStatus: 'Lecturer',
        day: 'wed',
        classLink: 'https://teams.microsoft.com/meet/44873993321984?p=xMQO8mA4OIDpdXEjD1',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'SE-103T',
        creditHours: 3,
        courseName: 'Object Oriented Programming Theory',
        startTime: 690,
        duration: 60,
        place: 'CG-6',
        logoName: 'ST',
        teacherName: 'Sir Tauseef Mubeen',
        teacherStatus: 'Lecturer',
        day: 'thu',
        classLink: 'https://teams.microsoft.com/meet/45836850298090?p=aPrj1qVJq2aJ07b7uW',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'MS-110T',
        creditHours: 3,
        courseName: 'Applied Physics Theory',
        startTime: 750,
        duration: 120,
        place: 'CG-6',
        logoName: 'MS',
        teacherName: 'Miss Sabeen Akhtar',
        teacherStatus: 'Lecturer',
        day: 'thu',
        classLink: 'https://teams.microsoft.com/meet/42937548930198?p=uuBqKq0QE9JtNx8jFk',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'SE-106L',
        creditHours: 1,
        courseName: 'Introduction To Software Engineering Lab',
        startTime: 870,
        duration: 180,
        place: 'CG-5',
        logoName: 'MS',
        teacherName: 'Miss Sarwat Fawwad',
        teacherStatus: 'Lecturer',
        day: 'thu',
        classLink: 'https://teams.microsoft.com/meet/45997636462488?p=Xp7wg6N6YCQM7Dzfg5',
        notAvailable: 'This is an in-person class'
    },
    {
        courseCode: 'MS-103',
        creditHours: 3,
        courseName: 'Calculus & Analytical Geometry',
        startTime: 510,
        duration: 120,
        place: 'MS Teams',
        logoName: 'MS',
        teacherName: 'Miss Sana Moiz',
        teacherStatus: 'Lecturer',
        day: 'fri',
        classLink: 'https://teams.microsoft.com/meet/41124712826591?p=ghmm27iGjOKIz5suKB'
    },
    {
        courseCode: 'SE-103T',
        creditHours: 3,
        courseName: 'Object Oriented Programming Theory',
        startTime: 630,
        duration: 120,
        place: 'MS Teams',
        logoName: 'ST',
        teacherName: 'Sir Tauseef Mubeen',
        teacherStatus: 'Lecturer',
        day: 'fri',
        classLink: 'https://teams.microsoft.com/meet/44673453311759?p=W84Jmbl9DzhEbFxQYB'
    },
    {
        courseCode: 'HS-103',
        creditHours: 3,
        courseName: 'Pakistan Studies And Aligarh Movement',
        startTime: 870,
        duration: 180,
        place: 'FG-1 / MS Teams',
        logoName: 'FN',
        teacherName: 'Miss Farah Naz',
        teacherStatus: 'Lecturer',
        day: 'sat',
        classLink: 'https://teams.microsoft.com/meet/46874061505440?p=AoUZNimpUYsFJtg862'
    }
]