import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify'
import { Analytics } from "@vercel/analytics/next"
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from '@/app/components/global_context';
import '@/app/assets/global.css';
import Navbar from "./components/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SE2C Time Table",
    description: "Generated by BilalCodeTM",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />

                {/* Android/Chrome browser bar color */}
                <meta name="theme-color" content="#f0c040" />

                {/* iOS PWA status bar */}
                <meta name="apple-mobile-web-app-capable" content="yes" />
                <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

                <link
                    href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap"
                    rel="stylesheet" />
            </head>
            <body className="min-h-full flex flex-col">
                <Analytics />
                <ToastContainer />
                
                <Navbar title="SCHEDULE"/>
                <ThemeProvider>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
