import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify'
import { Analytics } from "@vercel/analytics/next"
import { Geist, Geist_Mono } from "next/font/google";
import '@/app/assets/global.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "SE2C Time Table",
    description: "Generated by BilalCodeTM",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap"
                    rel="stylesheet" />
            </head>
            <body className="min-h-full flex flex-col">
                <Analytics />
                <ToastContainer />
                {children}
            </body>
        </html>
    );
}
